error_codes_dict = {
    "01": "Invalid command.",
    "02": "Command too long.",
    "03": "Command too short.",
    "04": "Invalid CRC.",
    "05": "Time-out on command execution.",
    "06": "Unable to setup new communication parameters. This occurs if one of the communication parameters is out range.",
    "07": "Incorrect number of parameters.",
    "08": "Invalid port handle selected.",
    "0A": "Invalid LED selected. The LED selected is out of range.",
    "0B": "Invalid LED state selected. The LED state selected is out of range.",
    "0C": "Command is invlaid while in the current operating mode.",
    "0D": "No tool is assigned to the selected port handle.",
    "0E": "Selected port handle not initialized. The port handle needs to be initialized before the command is sent.",
    "0F": "Selected port handle not enabled. The port handle needs to be enabled before the command is sent.",
            
    "10": "System not initialized. The system must be initialized before the command is sent.",
    "11": "Unable to stop tracking. This occurs if there are hardware problems. Please contact NDI.",
    "12": "Unable to start tracking. This occurs if there are hardware problems. Please contact NDI.",
    "13": "Unable to initialize the port handle.",
    "14": "Invalid Field Generator characterization parameters or incompatible hardware.",
    "15": "Unable to initialize the system. This occurs if:\n\t- the system could not return to Setup mode\n\t- there are internal hardware problems. Please contact NDI.",
    "16": "Unable to start Diagnostic mode. This occurs if there are hardware problems. Please contact NDI.",
    "17": "Unable to stop Diagnostic mode. This occurs if there are hardware problems. Please contact NDI.",
    "18": "Reserved.",
    "19": "Unable to read device's firmware revision information. This occurs if:\n\t- the processor selected is out of range\n\t- the system is unable to inquire firmware revision information from a processor",
    "1A": "Intern system error. This occurs when the system is unable to recover after a system processing exception.",
    "1B": "Reserved.",
    "1C": "Reserved.",
    "1D": "Unable to search for SROM device IDs",
    "1E": "Unable to read SROM device data. This occurs if the system is:\n\t- unable to auto-select the first SROM device on the given port handle as a target to read from\n\t- unable to read a page of SROM device data successfully",
    "1F": "Unable to write SROM device data. This can occur if:\n\t- the SROM device starting address is out of range\n\t- the system is unable to auto-select the first SROM device on the given port handle as a target for writing to\n\t- an SROM device on the given port handle has not previously been selected with the PSEL command as a target to write to\n\t- the system is unable to write a page of SROM device data successfully",
            
    "20": "Unable to select SROM device for given port handle and SROM device ID.",
    "21": "Reserved",
    "22": "Enabled tools are not supported by selected volume parameters.",
    "23": "Command parameters is out of range.",
    "24": "Unable to select parameters by volume. This occurs if:\n\t- the selected volume is not available\n\t- there are internal hardware errors. Please contact NDI.",
    "25": "Unable to determine the system's supported features list. This occurs if the system is unable to read all the hardware information.",
    "26": "Reserved.",
    "27": "Reserved.",
    "28": "Reserved.",
    "29": "Main processor firmware is corrupt",
    "2A": "No memory is available for dynamic allocation (heap is full).",
    "2B": "The requested port handle has not been allocated.",
    "2C": "The requested port handle has become unoccupied.",
    "2D": "All handles have been allocated.",
    "2E": "Incompatible firmware versions. This can occur if:\n\t- a firmware update failed\n\t- components with incompatible firmware are connected\nTo correct the problem, update the firmware.",
    "2F": "Reserved.",
            
    "30": "Reserved.",
    "31": "Invalid input or output state.",
    "32": "Invalid operation for the device associated with the specific port handle.",
    "33": "Feature not available.",
    "34": "Reserved.",
    "35": "Reserved.",
    "36": "Reserved.",
    "37": "Reserved.",
    "38": "Reserved.",
    "39": "Reserved.",
    "3A": "Reserved.",
    "3B": "Reserved.",
    "3C": "Reserved.",
    "3D": "Reserved.",
    "3E": "Reserved.",
    "3F": "Reserved.",

    "40": "Reserved.",
    "41": "Reserved.",
    "42": "Reserved.",
    "43": "Reserved.",
    "44": "Reserved.",
    "45": "Reserved.",
    "46": "Reserved.",
    "47": "Reserved.",
    "48": "Reserved.",
    "49": "Reserved.",
    "4A": "Reserved.",
    "4B": "Reserved.",
    "4C": "Reserved.",
    "4D": "Reserved.",
    "4E": "Reserved.",
    "4F": "Reserved.",

    "50": "Reserved.",
    "51": "Reserved.",
    "52": "Reserved.",
    "53": "Reserved.",
    "54": "Reserved.",
    "55": "Reserved.",
    "56": "Reserved.",
    "57": "Reserved.",
    "58": "Reserved.",
    "59": "Reserved.",
    "5A": "Reserved.",
    "5B": "Reserved.",
    "5C": "Reserved.",
    "5D": "Reserved.",
    "5E": "Reserved.",
    "5F": "Reserved.",

    "60": "Reserved.",
    "61": "Reserved.",
    "62": "Reserved.",
    "63": "Reserved.",
    "64": "Reserved.",
    "65": "Reserved.",
    "66": "Reserved.",
    "67": "Reserved.",
    "68": "Reserved.",
    "69": "Reserved.",
    "6A": "Reserved.",
    "6B": "Reserved.",
    "6C": "Reserved.",
    "6D": "Reserved.",
    "6E": "Reserved.",
    "6F": "Reserved.",

    "70": "Reserved.",
    "71": "Reserved.",
    "72": "Reserved.",
    "73": "Reserved.",
    "74": "Reserved.",
    "75": "Reserved.",
    "76": "Reserved.",
    "77": "Reserved.",
    "78": "Reserved.",
    "79": "Reserved.",
    "7A": "Reserved.",
    "7B": "Reserved.",
    "7C": "Reserved.",
    "7D": "Reserved.",
    "7E": "Reserved.",
    "7F": "Reserved.",

    "80": "Reserved.",
    "81": "Reserved.",
    "82": "Reserved.",
    "83": "Reserved.",
    "84": "Reserved.",
    "85": "Reserved.",
    "86": "Reserved.",
    "87": "Reserved.",
    "88": "Reserved.",
    "89": "Reserved.",
    "8A": "Reserved.",
    "8B": "Reserved.",
    "8C": "Reserved.",
    "8D": "Reserved.",
    "8E": "Reserved.",
    "8F": "Reserved.",

    "90": "Reserved.",
    "91": "Reserved.",
    "92": "Reserved.",
    "93": "Reserved.",
    "94": "Reserved.",
    "95": "Reserved.",
    "96": "Reserved.",
    "97": "Reserved.",
    "98": "Reserved.",
    "99": "Reserved.",
    "9A": "Reserved.",
    "9B": "Reserved.",
    "9C": "Reserved.",
    "9D": "Reserved.",
    "9E": "Reserved.",
    "9F": "Reserved.",

    "A0": "Reserved.",
    "A1": "Reserved.",
    "A2": "Reserved.",
    "A3": "Reserved.",
    "A4": "Reserved.",
    "A5": "Reserved.",
    "A6": "Reserved.",
    "A7": "Reserved.",
    "A8": "Reserved.",
    "A9": "Reserved.",
    "AA": "Reserved.",
    "AB": "Reserved.",
    "AC": "Reserved.",
    "AD": "Reserved.",
    "AE": "Reserved.",
    "AF": "Reserved.",

    "B0": "Reserved.",
    "B1": "Reserved.",
    "B2": "Reserved.",
    "B3": "Reserved.",
    "B4": "Reserved.",
    "B5": "Reserved.",
    "B6": "Reserved.",
    "B7": "Reserved.",
    "B8": "Reserved.",
    "B9": "Reserved.",
    "BA": "Reserved.",
    "BB": "Reserved.",
    "BC": "Reserved.",
    "BD": "Reserved.",
    "BE": "Reserved.",
    "BF": "Reserved.",

    "C0": "Reserved.",
    "C1": "Reserved.",
    "C2": "Command not supported by proxy",
    "C3": "Offline fit not possible, eg no or incompatible DLL.",
    "C4": "Incompatible replies from two SCUs, eg different firmware revisions",
    "C5": "Reserved.",
    "C6": "Reserved.",
    "C7": "Reserved.",
    "C8": "Reserved.",
    "C9": "Reserved.",
    "CA": "Reserved.",
    "CB": "Reserved.",
    "CC": "Reserved.",
    "CD": "Reserved.",
    "CE": "Reserved.",
    "CF": "Reserved.",

    "D0": "Reserved.",
    "D1": "Reserved.",
    "D2": "Reserved.",
    "D3": "Reserved.",
    "D4": "Reserved.",
    "D5": "Reserved.",
    "D6": "Reserved.",
    "D7": "Reserved.",
    "D8": "Reserved.",
    "D9": "Reserved.",
    "DA": "Reserved.",
    "DB": "Reserved.",
    "DC": "Reserved.",
    "DD": "Reserved.",
    "DE": "Reserved.",
    "DF": "Reserved.",

    "E0": "Reserved.",
    "E1": "Reserved.",
    "E2": "Reserved.",
    "E3": "Reserved.",
    "E4": "Reserved.",
    "E5": "Reserved.",
    "E6": "Reserved.",
    "E7": "Reserved.",
    "E8": "Reserved.",
    "E9": "Reserved.",
    "EA": "Reserved.",
    "EB": "Reserved.",
    "EC": "Reserved.",
    "ED": "Reserved.",
    "EE": "Reserved.",
    "EF": "Reserved.",

    "F0": "Reserved.",
    "F1": "Reserved.",
    "F2": "Reserved.",
    "F3": "Reserved.",
    "F4": "Unable to erase Flash SROM device.",
    "F5": "Unable to write Flash SROM device",
    "F6": "Unable to read Flash SROM device.",
    "F7": "Reserved.",
    "F8": "Reserved.",
    "F9": "Reserved.",
    "FA": "Reserved.",
    "FB": "Reserved.",
    "FC": "Reserved.",
    "FD": "Reserved.",
    "FE": "Reserved.",
    "FF": "Reserved."
}